---
date: "May 13, 2016"
output:
  html_document:
    toc: yes
    toc_float: yes
---

Гайд по карьерным сетям ЛК
============

-----------------------------------------------
Юля, привет! 

Это гайдлайн по ведению карьерных социальных медиа АО "Лаборатория Касперского" (далее - ЛК).

Здесь я расскажу о том, что у нас есть, как мы организуем работу и что планируем получить на выходе. 

По всем вопросам и уточнениям можешь обращаться ко мне: 

Вконтактике:
[vk.com/nejel](https://vk.com/nejel)

В почте:
[Alexander.nezhelsky@kaspersky.com](Alexander.nezhelsky@kaspersky.com)

Или по телефону/телеграму:
+ 7 929 065 37 42
-----------------------------------------------

С чем работать?
---------

Наши социальные сети «О карьере»: 




**1.  Kaspersky Lab | Карьера **; Вконтакте
[vk.com/kaspercareer](https://vk.com/kaspercareer)

*Созадна 16 августа 2015 года*
    
Вконтактик - отправная точка наших социальных медиа. Именно здесь происходят основные движения, работа над текстом. Большая часть постов запиливается, в первую очередь, именно сюда и лишь позже расходится по других соц.сетям, меняясь в формате.


**2.  Kaspersky Lab | События**; в Фейсбуке [facebook.com/kaspercareer/](https://www.facebook.com/kaspercareer)

*Созадна в январе 2016 года*

**3.  Kaspersky Job**; в Твиттере [/@kasperskyjob](https://twitter.com/kasperskyjob)

*Созадна в мае 2016 года*

**4.  Kaspersky Lab**; в LinkedIn [Kaspersky Lab](http://www.linkedin.com/company/8699)

*Созадна до 2015 года*

**5.  Kaspersky Lab**; в Glassdoor [Kaspersky Lab](https://www.glassdoor.com/Overview/Working-at-Kaspersky-Lab-EI_IE19041.11,24.htm)

*Созадна до 2015 года*

Но ты, по своим рабочим задачам, будешь заниматься только первыми тремя из них.

Как работать? 
----------

**Кто пишет посты сейчас?**

Наша команда авторов — отважные герои фронта информационной безопасности. 
К ЛК они присоединились в сентябре 2015, поступив на программу стажировок SAFEBOARD (кстати, скоро новый набор на SAFEBOARD 2016). 
В рамках программы SAFEBOARD мы набрали 65 человек стажёров, которые работают в ЛК на 4 разных направлениях: 

1.	Вирусная аналитика
2.	Разработка
3.	Тестирование
4.	Системное администрирование

Из этих 65 человек весной 2016 мы отобрали 6 самых смелых – SAFEBOARD Champions (или просто Амбассадоры). Эти отважные парни и девушки помогают нам проводить мероприятия, представляют нас в вузах и помогают в социальных медиа (пишут тексты).

**Так кто все эти люди?**

Наши 6 Амбассадоров разбиты на 3 команды:

Команда "СМ":

* [Кузнецова Мария](https://vk.com/kuznetmaria)

* [Онфриев Сергей](https://vk.com/onsevl)

Команда "Свитер":

* [Котенева Алёна](https://vk.com/id244567326)

* [Васюта Макарий](https://vk.com/mvasuta)

Команда "А":

* [Жаболенко Антон](https://vk.com/i_am_anton)

* [Михайлов Владимир](https://vk.com/goohard)

Эти 6 ребят и пишут бОльшую часть постов на текущий момент. Тебе предстоит долго и тесно с ними работать, поэтому постарайся заранее подготовиться к этому: изучи их, познакомься, по возможности. Если что я могу тебя представить.

**А как работать?**

Сложный и правильный вопрос - как построить работу в команде? 

Мы организуем это следующим образом:

Одну часть постов пишут Амбассадоры: 

Ты пингуешь команды (3 шт.) на предмет того, что им пора запиливать посты. Руководствуясь списком источников (о нём ниже) и своим вкусом, ребята запиливают какие-то тексты технического плана в одну из рубрик. После этого тексты передаются тебе на вычитку и правки. Ты проверяешь их грамматику, стилистику, правишь правки, добавляешь хэштеги, делаешь визуалы по корпоративному шаблону в фотошопе и в назначенное время ставишь в таймер. 
После этого скидвыаешь мне коротенькое сообщение в духе "в таймер на столько-то и столько-тозаряжены посты, проверь". Я проверяю их, вношу правки, если необходимо и посты выходят по таймеру в положенный им срок.

Вторую часть постов пишешь ты:

В неё входят:

* Посты о карьере вообще
* О карьере в IT
* О работе ЛК
* Интервью с сотрудниками
* Материалы с наших событий
* Другое

KPI
--------------------

В конце года мы проведём оценку наших успехов.
Индикаторы такие:

* 5000 подписчиков в ВК
* 3000 подписчиков в ФБ
* 2000 регистраций на [сайте событий](https://events.kaspersky.com/) (не имеет тебе прямого отношения, но имей в виду)

Дополнительно
--------------------

Список источников, шаблон визуала для фотошопа, описание программы Амбассадоров, рубрикатор для группы и небольшой гайд по постингу лежат [вот тут](https://cloud.mail.ru/public/VhVT/GWzWRKC3o). Внимательно изучи все эти документы.
